package com.entity;
// Generated Oct 5, 2023, 8:54:31 AM by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Category generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "category", catalog = "memetube")
public class Category{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Idcategory", unique = true, nullable = false)
	private Integer idcategory;
	@Column(name = "Name", length = 100)
	private String name;
	@OneToMany(mappedBy = "category")
	@JsonIgnore
	private List<Video> videos = new ArrayList<>();
}
