package com.entity;
// Generated Oct 5, 2023, 8:54:31 AM by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Channel generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "channel", catalog = "memetube", uniqueConstraints = @UniqueConstraint(columnNames = "Iduser"))
public class Channel{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Idchannel", unique = true, nullable = false)
	private Integer idchannel;
	@ManyToOne
	@JoinColumn(name = "Iduser", unique = true)
	private Users users;
	@Temporal(TemporalType.DATE)
	@Column(name = "Datecreated", length = 10)
	private Date datecreated;
	@Column(name = "Status")
	private Boolean status;
	@Column(name = "Channelname")
	private String channelname;
	@OneToMany( mappedBy = "channel")
	@JsonIgnore
	private List<Subscribe> subcribes = new ArrayList<>();
	@OneToMany(mappedBy = "channel")
	@JsonIgnore
	private List<Video> videos = new ArrayList<>();

}
