package com.entity;
// Generated Oct 7, 2023, 1:04:35 AM by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Playlist generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "playlist", catalog = "memetube")
public class Playlist{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idplaylist", unique = true, nullable = false)
	private Integer idplaylist;
	@Column(name = "idchannel")
	private Integer idchannel;
	@Column(name = "name", length = 100)
	private String name;
	@JsonIgnore
	@OneToMany(mappedBy = "playlist")
	private List<Pldetail> pldetails = new ArrayList<>();


}
