package com.entity;
// Generated Oct 5, 2023, 8:54:31 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Rating generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "rating", catalog = "memetube")
public class Rating{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Idrating", unique = true, nullable = false)
	private Integer idrating;
	@ManyToOne
	@JoinColumn(name = "Iduser")
	private Users users;
	@ManyToOne
	@JoinColumn(name = "Idvideo")
	private Video video;
	@Column(name = "Rate")
	private Boolean rate;
	@Column(name = "Datecreated")
	private Timestamp datecreate;
}
