package com.entity;
// Generated Oct 5, 2023, 8:54:31 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Subcribe generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "subscribe", catalog = "memetube")
public class Subscribe{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Idsub", unique = true, nullable = false)
	private Integer idsub;
	@ManyToOne
	@JoinColumn(name = "Idchannel")
	private Channel channel;
	@ManyToOne
	@JoinColumn(name = "Iduser")
	private Users users;
}
