package com.entity;
// Generated Oct 5, 2023, 8:54:31 AM by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Video generated by hbm2java
 */
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Data
@Table(name = "video", catalog = "memetube")
public class Video{
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Idvideo", unique = true, nullable = false)
	private Integer idvideo;
	@ManyToOne
	@JoinColumn(name = "Idcategory")
	private Category category;
	@ManyToOne
	@JoinColumn(name = "Idchannel")
	private Channel channel;
	@Column(name = "Title", length = 200)
	private String title;
	@Column(name = "Imageurl")
	private String imageurl;
	@Column(name = "Describes")
	private String describes;
	@Column(name = "Videourl")
	private String videourl;
	@Temporal(TemporalType.DATE)
	@Column(name = "Datecreated", length = 10)
	private Date datecreated;
	@Column(name = "Status")
	private Boolean status;
	@Column(name = "Viewcount")
	private Long viewcount;
	@OneToMany(mappedBy = "video")
	@JsonIgnore
	private List<Comment> comments = new ArrayList<>();
	@OneToMany(mappedBy = "video")
	@JsonIgnore
	private List<Rating> ratings = new ArrayList<>();
}
